# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 19:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_date', models.DateTimeField()),
                ('is_present', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(default=None, max_length=200)),
                ('course_code', models.CharField(default=None, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_no', models.CharField(default=None, max_length=50)),
                ('first_name', models.CharField(default=None, max_length=200)),
                ('last_name', models.CharField(default=None, max_length=200)),
                ('email', models.EmailField(default=None, max_length=254)),
                ('current_semester', models.IntegerField()),
                ('is_active', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField()),
                ('section', models.CharField(default=None, max_length=50)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance_portal.Course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance_portal.Student')),
            ],
        ),
        migrations.AddField(
            model_name='attendance',
            name='student_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance_portal.StudentCourse'),
        ),
    ]
