# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='lecture_type',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='attendance',
            name='no_of_lectures',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='student',
            name='graduation_year',
            field=models.IntegerField(default=2020),
            preserve_default=False,
        ),
    ]
