# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-03 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_portal', '0002_auto_20170602_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='enrollment_no',
            field=models.CharField(default=None, max_length=50, unique=True),
        ),
    ]
