# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 17:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_portal', '0005_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='is_open',
        ),
    ]
