# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 00:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_portal', '0006_remove_session_is_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcourse',
            name='lectures_attended',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentcourse',
            name='total_lectures',
            field=models.IntegerField(default=0),
        ),
    ]
