# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_portal', '0007_auto_20170605_0028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentcourse',
            name='total_lectures',
        ),
        migrations.AddField(
            model_name='course',
            name='total_lectures',
            field=models.IntegerField(default=0),
        ),
    ]
