# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 00:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_portal', '0008_auto_20170605_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='current_semester',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='graduation_year',
            field=models.IntegerField(null=True),
        ),
    ]
