# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 18:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_portal', '0009_auto_20170606_0004'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=None, max_length=100)),
                ('token_issued', models.IntegerField(default=0)),
                ('token_accepted', models.IntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance_portal.Course')),
            ],
        ),
        migrations.AddField(
            model_name='professor',
            name='courses',
            field=models.ManyToManyField(to='attendance_portal.Course'),
        ),
    ]
