# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 22:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_portal', '0010_auto_20170607_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancetoken',
            name='lecture_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 7, 22, 58, 28, 332903)),
            preserve_default=False,
        ),
    ]
