# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 23:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_portal', '0011_attendancetoken_lecture_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_date', models.DateTimeField()),
                ('no_of_lectures', models.IntegerField(default=None)),
                ('lecture_type', models.CharField(default=None, max_length=50)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance_portal.Course')),
            ],
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='lecture_date',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='lecture_type',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='no_of_lectures',
        ),
        migrations.RemoveField(
            model_name='attendancetoken',
            name='course',
        ),
        migrations.RemoveField(
            model_name='attendancetoken',
            name='lecture_date',
        ),
        migrations.AddField(
            model_name='attendance',
            name='token',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
