# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-10 00:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_portal', '0013_auto_20170609_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='professor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='attendance_portal.Professor'),
            preserve_default=False,
        ),
    ]
