# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-14 22:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_portal', '0014_lecture_professor'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.IntegerField(default=0),
        ),
    ]
