# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-26 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_portal', '0015_course_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='rating',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lecture',
            name='rating',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
