# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-29 23:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_portal', '0016_auto_20170826_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
    ]
