# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-30 00:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_portal', '0017_auto_20170829_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='feedback',
            field=models.TextField(default='okay'),
            preserve_default=False,
        ),
    ]
